# -*- coding: utf-8 -*-
"""traindataNYC.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1ejwNiXs_zFYIInFo2zbBBW57krYtB1-D
"""

import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt

df = pd.read_csv('2020_turnstile_daily_count.csv', sep=',', low_memory=False)
columns_to_drop = ['daytime_routes', 'division','line', 'structure', 'gtfs_longitude', 'gtfs_latitude', 'complex_id']
df.drop(columns= columns_to_drop,inplace=True)
df = df.dropna()
print(df)

def NYCturnstileDictionary():
  borough=[]
  for i in df['borough']:
    if i not in borough:
      borough.append(i)
  print(borough)

  stop_data = dict()
  for i in borough:
    stop_entries = df.loc[df['borough'] == i, 'entries']
    stop_exits = df.loc[df['borough'] == i, 'exits']
    stop_data[i] = (stop_entries, stop_exits)
  return stop_data

NYCturnstileDictionary()